services:
  db_mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=crypto
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    restart: always

    volumes:
      - 'mysql_data:/var/lib/mysql'
  crypto_app:
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - './:/code'
    command: npm run dev:crypto:backend
    depends_on:
      - db_mysql
volumes:
  mysql_data:

