services:
  Coin.CoinRepository:
    class: ../../../../../Contexts/Crypto/Coin/infrastructure/MySqlCoinRepository
    arguments: ['@Shared.ConnectionManager']

  Coin.searchAll.AllCoinsSearcher:
    class: ../../../../../Contexts/Crypto/Coin/application/searchAll/AllCoinsSearcher
    arguments: ['@Coin.CoinRepository']

  Coin.searchAll.SearchAllCoinsQueryHandler:
    class: ../../../../../Contexts/Crypto/Coin/application/searchAll/SearchAllCoinsQueryHandler
    arguments: ['@Coin.searchAll.AllCoinsSearcher']
    tags:
      - { name: 'queryHandler' }

  Coin.create.CoinCreator:
    class: ../../../../../Contexts/Crypto/Coin/application/create/CoinCreator
    arguments: [ '@Coin.CoinRepository', '@Shared.EventBus']

  Coin.create.CreateCoinCommandHandler:
    class: ../../../../../Contexts/Crypto/Coin/application/create/CreateCoinCommandHandler
    arguments: [ '@Coin.create.CoinCreator' ]
    tags:
      - { name: 'commandHandler' }
