services:
  Apps.crypto.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.crypto.controllers.CoinsGetController:
    class: ../../controllers/Coin/CoinsGetController
    arguments: ['@Shared.QueryBus']

  Apps.crypto.controllers.CoinPutController:
    class: ../../controllers/Coin/CoinPutController
    arguments: [ '@Shared.CommandBus' ]
